### ISSUE TITLE
I can add point to myself

### ISSUE THREAD

**Issue by nadapapa** [nadapapa/baas#1]

**Comment by BalazsKovacs** [comment]
backenden le lehet kezelni, vagy elég kliens oldalon?

**Comment by nadapapa** [comment]
valszeg megoldható backenden, frontenden meg (csak) kezelni kell az elutasítást

vagy db rule: https://firebase.google.com/docs/database/security/
vagy function: https://firebase.google.com/docs/functions/

**Comment by BalazsKovacs** [comment]
Mondjuk én kliens oldalon is lekezelném, nem is kellene lehetőséget adni (persze ettől még a backenden is le kell kezelni), de ne legyen lehetőség egy mindig hibát dobó akcióra.
